apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: image-monitor
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - pods
      - deploymentconfigs
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'