kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heimdall
subjects:
  - kind: ServiceAccount
    name: heimdall
    namespace: heimdall
roleRef:
  kind: ClusterRole
  name: heimdall
  apiGroup: rbac.authorization.k8s.io
