apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: heimdall
rules:
- apiGroups:
  - ""
  - apps.openshift.io
  resources:
  - pods
  - deploymentconfigs
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - imagemonitor.integreatly.org
  resources:
  - '*'
  verbs:
  - '*'
